name: "Joke Action"
description: "Fetches a random joke and exposes it as an output"

outputs:
  joke:
    description: "The fetched joke text"

runs:
  using: 'node24' # or node20 / node24 depending on your runner preference
  main: 'dist/index.js'